# -*- coding: utf-8 -*-
"""area_rectangle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOlP_9z_38DLmprXta1CMu5ukowEEzH4
"""

# Program that calculates area of a rectangel given length and width

def area_rectangle(length, width):
  """
  ..........Arguments.....................
   takes floats or integer numbers as length and width

  ..........Return.............
  returns the product of the two values used as argument.
  """
  return(print(f'The area of the rectangle is: {length * width}'))

area_rectangle(4/5, 10)