# -*- coding: utf-8 -*-
"""sum_two_numbers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FU3UtB87ekhWuhV2D5TlYBSg0sWIDz_O
"""

# Program that calculate the sum of two numbers entered by user.

try:
  # import ast
  import ast

  # take numbers from user and match with the specific data type
  first_digit = ast.literal_eval(input('Enter your first number:'))
  second_digit = ast.literal_eval(input('Enter your second number:'))

  # add the two numbers and print
  print(first_digit + second_digit)
except ValueError:
  print('You did not type a number. Check and try again.')